project:
  type: website

website:
  title: "PENYELIDIK JENAYAH ğŸ‘®ğŸ½ğŸ‘®ğŸ½â€â™‚ğŸ‘®ğŸ½â€â™€ï¸ï¸ï¸"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Project Proposal
      - href: poster.qmd
        text: Project Poster
      - href: datapreprocessing.qmd
        text: Data Pre-processing
      - href: userguide.qmd
        text: User Guide
      - href: https://jeffery-gaa.shinyapps.io/penyelidik-jenayah/
        text: Shiny Application

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

